export const MARKETING_CHANNELS = ['linkedin', 'email', 'google', 'meta', 'organic', 'event', 'referral', 'other'] as const;
export const MARKETING_STAGES = ['accepted', 'rejected', 'demo', 'pilot', 'paid'] as const;
export type MarketingSection = 'today' | 'campaigns' | 'leads' | 'connections';
export type MarketingCampaign = { id: string; name: string; audience: string; offer: string; channel: string; status: string; spend_gbp: number; success_measure: string; review_on: string | null };
export type MarketingFeedback = { lead_id: string; user_id: string; stage: string; reason: string };
export type MarketingLead = { id: string; campaign_id: string; company_name: string; contact_name: string; contact_email: string; company_size: string; notes: string; assigned_to_user_id: string | null; created_at: string };
export type MarketingTask = { id: string; text: string; status: string; due_at: string | null; payload: Record<string, unknown> | null };
export type MarketingMember = { userId: string; name: string };
export type MarketingConnection = { provider: string; property_id: string; snapshot: { users: number; sessions: number; keyEvents: number; period: string } | null; synced_at: string | null };
export type MarketingData = { canManage: boolean; userId: string; campaigns: MarketingCampaign[]; leads: MarketingLead[]; feedback: MarketingFeedback[]; tasks: MarketingTask[]; members: MarketingMember[]; connections: MarketingConnection[]; fetchedAt: string; limited: boolean };
export const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
export function marketingText(value: unknown, max: number, required = false): string {
  if (typeof value !== 'string' || value.length > max || (required && !value.trim())) throw new Error(`Enter valid text${required ? ' in each required field' : ''} (maximum ${max} characters)`);
  return value.trim();
}
export function marketingSpend(value: unknown): number {
  if ((typeof value !== 'number' && typeof value !== 'string') || String(value).trim() === '') throw new Error('Enter recorded campaign spend, including 0 for a campaign with no spend');
  const amount = Number(value);
  if (!Number.isFinite(amount) || amount < 0 || amount > 9999999999.99) throw new Error('Enter a valid non-negative spend in pounds');
  return Math.round(amount * 100) / 100;
}
export function marketingDate(value: unknown): string {
  const date = String(value || '');
  if (!/^\d{4}-\d{2}-\d{2}$/.test(date) || !Number.isFinite(Date.parse(date)) || new Date(date).toISOString().slice(0, 10) !== date) throw new Error('Choose a valid review date');
  return date;
}
export function marketingMetrics(campaigns: MarketingCampaign[], leads: MarketingLead[], feedback: MarketingFeedback[]) {
  const stages = new Map(feedback.map(row => [row.lead_id, row.stage]));
  const accepted = leads.filter(row => ['accepted', 'demo', 'pilot', 'paid'].includes(stages.get(row.id) || '')).length;
  const rejected = leads.filter(row => stages.get(row.id) === 'rejected').length;
  const demos = leads.filter(row => ['demo', 'pilot', 'paid'].includes(stages.get(row.id) || '')).length;
  const paid = leads.filter(row => stages.get(row.id) === 'paid').length;
  const spend = campaigns.reduce((total, row) => total + Number(row.spend_gbp || 0), 0);
  return { leads: leads.length, accepted, rejected, demos, paid, spend, costPerAccepted: accepted ? spend / accepted : null, unassigned: leads.filter(row => !row.assigned_to_user_id).length, awaiting: leads.filter(row => row.assigned_to_user_id && !stages.has(row.id)).length };
}
export function marketingReportIsLimited(results: { count: number | null; data: unknown[] | null }[]): boolean {
  return results.some(row => row.count == null || row.count > (row.data?.length || 0) || (row.data?.length || 0) > 1000);
}
type CoachStep = { title: string; detail: string; simple: string; output: string };
export type CoachApproach = { id: string; name: string; tradeoff: string; steps: CoachStep[] };
const step = (title: string, detail: string, simple: string, output: string): CoachStep => ({ title, detail, simple, output });
export const MARKETING_LESSONS: Record<MarketingSection, { title: string; purpose: string; approaches: CoachApproach[] }> = {
  today: { title: 'Turn your priorities into a useful plan', purpose: 'Start with a real bottleneck. Choose the approach, then define what success looks like.', approaches: [
    { id: 'sales-feedback', name: 'Review lead quality with sales', tradeoff: 'Recommended when feedback is missing or leads are unsuitable. Needs time with sales.', steps: [step('Read the evidence', 'Review rejected leads and those waiting for a response. Ask Cam or Sharon what prevented progress. Avoid changing the audience based on one vague comment.', 'Ask why each lead did not progress.', 'A clear reason recorded against each lead.'), step('Choose one improvement', 'Agree what a suitable buyer looks like: screening need, volume, decision-maker and timing. Choose one form question, audience change or follow-up to test.', 'Agree what a good lead looks like. Change one thing.', 'A change linked to a specific buyer problem.'), step('Set the review', 'Record a deadline and success measure. Compare sales-accepted leads and demos, allowing time for the test to generate responses.', 'Pick a date and how you will know it worked.', 'One action with an owner, review date and measure.')] },
    { id: 'quick-test', name: 'Run a small campaign test', tradeoff: 'Faster to start. Risks testing the wrong problem if qualification is unclear.', steps: [step('Define the buyer problem', 'Choose one buyer segment and one problem Interviewa can demonstrably solve. Use current sales feedback and approved claims.', 'Choose one customer group and one real problem.', 'A specific audience and offer.'), step('Test one variable', 'Keep the test small and change only the message, audience or landing page. Record spend and campaign source.', 'Change one thing and track it.', 'A campaign record with traceable leads.'), step('Judge commercial results', 'Review accepted leads and demos rather than likes alone. Record whether to keep, revise or stop the test.', 'Check whether it produced useful sales conversations.', 'A decision backed by the test results.')] }
  ] },
  campaigns: { title: 'Build a campaign around a commercial outcome', purpose: 'Define the audience, offer, channel and success measure before starting.', approaches: [
    { id: 'improve', name: 'Improve an existing campaign', tradeoff: 'Recommended when you have usable results. Requires reliable source tracking.', steps: [step('Check the baseline', 'Open the campaign and check recorded spend, sourced leads and sales feedback. Identify missing data before comparing results.', 'Make sure you can trust the numbers.', 'A baseline with gaps clearly marked.'), step('Find the weak stage', 'Is the problem generating enquiries, qualifying buyers, arranging demos or converting pilots? Choose the stage the evidence supports.', 'Find where good prospects stop moving forward.', 'One bottleneck to address.'), step('Record the next test', 'Update the campaign success measure and review date. Change one thing and keep the previous results for comparison.', 'Choose one change and a date to check it.', 'A test with a measurable outcome.')] },
    { id: 'new-offer', name: 'Test a different offer', tradeoff: 'Explores a new angle. Needs a separate campaign so results do not get mixed.', steps: [step('Choose the offer', 'Use a buyer problem from sales feedback. Explain the practical result and avoid unverified savings claims.', 'Say what problem you help the buyer solve.', 'A clear offer for a specific audience.'), step('Create a separate record', 'Record the channel, spend, success measure and review date. Give every resulting lead the correct campaign.', 'Keep the new test separate and label its leads.', 'A traceable campaign.'), step('Review quality', 'Compare acceptance and demos when enough feedback is available. Document the limitations of a small sample.', 'Check the quality of leads, not just how many arrived.', 'An evidence-based decision.')] }
  ] },
  leads: { title: 'Give sales a lead they can act on', purpose: 'Capture the buyer context and preserve the campaign source. Sales records acceptance or rejection.', approaches: [
    { id: 'qualify', name: 'Qualify before handing over', tradeoff: 'Recommended for uncertain fit. Adds a step but protects sales time.', steps: [step('Capture fit', 'Record the company, contact, approximate size and screening problem. Keep unknown details labelled as unknown.', 'Write down who they are and what help they need.', 'Useful buyer context without invented facts.'), step('Assign the next step', 'Choose the salesperson and describe what should happen next. Preserve the campaign that generated the lead.', 'Choose who will follow up and why.', 'A named owner and clear next action.'), step('Close the feedback loop', 'Ask the assigned salesperson to accept or reject with a reason, then update demo, pilot and paid outcomes when confirmed.', 'Get sales feedback and use it to improve the next campaign.', 'An outcome that helps targeting.')] },
    { id: 'fast-handover', name: 'Hand over an urgent enquiry', tradeoff: 'Protects speed for interested buyers. Sales may need to fill qualification gaps.', steps: [step('Capture the essentials', 'Record the contact, company, campaign source and exact request. State what still needs checking.', 'Save enough information to make the first call.', 'A traceable enquiry with gaps visible.'), step('Choose the salesperson', 'Assign the lead to the appropriate active salesperson and include the urgency in the notes.', 'Give it to someone who can respond.', 'A clear sales owner.'), step('Check the response', 'Review the lead after the first contact. Get acceptance or rejection feedback and revise the targeting if needed.', 'Check what happened and record the result.', 'Feedback rather than a forgotten handover.')] }
  ] },
  connections: { title: 'Connect the data you need to make decisions', purpose: 'Start with the tools already in use. Analytics activity and CRM sales outcomes measure different things.', approaches: [
    { id: 'website', name: 'Connect Google Analytics', tradeoff: 'Recommended for website visibility. Requires property access and Analytics consent.', steps: [step('Choose the property', 'Find the numeric GA4 property ID in Google Analytics. Use a Google account with access to the Interviewa property.', 'Find the property number and an account that can view it.', 'A verified property and account.'), step('Grant access and refresh', 'Connect Google with Analytics access, save the property ID and refresh. Check the reporting period and last sync.', 'Connect the right account, then load the numbers.', 'A dated website snapshot.'), step('Check conversion tracking', 'Confirm which events are marked as key events in GA4. A key event is not automatically a qualified lead or customer.', 'Check what each event means before treating it as a lead.', 'Website tracking with clear definitions.')] },
    { id: 'crm-first', name: 'Start with campaign and CRM records', tradeoff: 'Works without external connectors. Requires disciplined entry and sales feedback.', steps: [step('Record campaigns', 'Enter the campaign audience, offer, channel and cumulative spend. Use 0 only when no spend has actually occurred.', 'Keep a simple record of each campaign and its cost.', 'Campaigns you can compare.'), step('Attach every lead', 'Choose the campaign on each lead. Record context and a sales owner, then ask sales to record outcomes.', 'Label every lead and follow it through sales.', 'Traceable leads and outcomes.'), step('Reconcile the report', 'Compare recorded spend against provider bills and sales outcomes against CRM evidence. Fill gaps before the board report.', 'Check your records against what actually happened.', 'A report with known limitations.')] }
  ] }
};
export const OWN_APPROACH: CoachApproach = { id: 'own', name: 'My own approach', tradeoff: 'Choose your method. Explain why and how you will test it.', steps: [step('Describe your idea', 'Explain the specific change, buyer problem and evidence supporting it.', 'What will you do, and why?', 'A clear proposal.'), step('Check the trade-offs', 'List the time, budget, data and help needed. Identify what could invalidate your idea.', 'What will it cost, and what could go wrong?', 'A practical test with limitations.'), step('Set the result', 'Choose an owner, review date and success measure. Ask Brain to challenge your plan if you need more help.', 'Decide when to check it and what success means.', 'An action you can evaluate.')] };
