const CANONICAL_PRODUCTION_ORIGIN = "https://www.livecoachcrm.com";

function normalizedOrigin(value: string | undefined): string | null {
  const raw = String(value || "").trim();
  if (!raw) return null;

  try {
    const url = new URL(/^https?:\/\//i.test(raw) ? raw : `https://${raw}`);
    if (url.protocol !== "http:" && url.protocol !== "https:") return null;
    return url.origin;
  } catch {
    return null;
  }
}

function isLocalOrPrivateOrigin(origin: string): boolean {
  const hostname = new URL(origin).hostname.toLowerCase().replace(/^\[|\]$/g, "");
  if (
    hostname === "localhost" ||
    hostname === "0.0.0.0" ||
    hostname === "::1" ||
    hostname.endsWith(".local") ||
    hostname.endsWith(".internal")
  ) {
    return true;
  }
  if (/^127\./.test(hostname)) return true;
  if (/^10\./.test(hostname)) return true;
  if (/^192\.168\./.test(hostname)) return true;
  if (/^169\.254\./.test(hostname)) return true;
  if (/^172\.(1[6-9]|2[0-9]|3[0-1])\./.test(hostname)) return true;
  return false;
}

/**
 * Resolve the origin used in links that leave LiveCoach, such as invitation
 * and daily brief emails. A stale local development value must never leak
 * into an email generated by a Vercel deployment.
 */
export function publicAppOrigin(requestOrigin?: string): string {
  const deployed =
    process.env.VERCEL === "1" ||
    process.env.VERCEL_ENV === "production" ||
    process.env.VERCEL_ENV === "preview";

  const configured = normalizedOrigin(process.env.NEXT_PUBLIC_APP_URL);
  if (
    configured &&
    (!deployed ||
      (configured.startsWith("https://") && !isLocalOrPrivateOrigin(configured)))
  ) {
    return configured;
  }

  if (deployed) {
    // External links must remain on the official domain even if Vercel's
    // project-owned production alias still points at the legacy vercel.app
    // address. Internal preview-to-preview calls are handled separately below.
    return CANONICAL_PRODUCTION_ORIGIN;
  }

  const request = normalizedOrigin(requestOrigin);
  return request || CANONICAL_PRODUCTION_ORIGIN;
}

/**
 * Resolve the current deployment for authenticated server-to-server calls.
 * Unlike public email links, a preview must call its own preview function and
 * not silently invoke production. VERCEL_URL is deployment-owned, not taken
 * from an untrusted browser Host header.
 */
export function internalAppOrigin(requestOrigin?: string): string {
  const deployment = normalizedOrigin(process.env.VERCEL_URL);
  if (
    deployment?.startsWith("https://") &&
    !isLocalOrPrivateOrigin(deployment)
  ) {
    return deployment;
  }
  return publicAppOrigin(requestOrigin);
}
