const CANONICAL_PRODUCTION_ORIGIN = "https://livecoach-alpha.vercel.app";

function normalizedOrigin(value: string | undefined): string | null {
  const raw = String(value || "").trim();
  if (!raw) return null;

  try {
    const url = new URL(/^https?:\/\//i.test(raw) ? raw : `https://${raw}`);
    if (url.protocol !== "http:" && url.protocol !== "https:") return null;
    return url.origin;
  } catch {
    return null;
  }
}

function isLocalOrPrivateOrigin(origin: string): boolean {
  const hostname = new URL(origin).hostname.toLowerCase().replace(/^\[|\]$/g, "");
  if (
    hostname === "localhost" ||
    hostname === "0.0.0.0" ||
    hostname === "::1" ||
    hostname.endsWith(".local") ||
    hostname.endsWith(".internal")
  ) {
    return true;
  }
  if (/^127\./.test(hostname)) return true;
  if (/^10\./.test(hostname)) return true;
  if (/^192\.168\./.test(hostname)) return true;
  if (/^169\.254\./.test(hostname)) return true;
  if (/^172\.(1[6-9]|2[0-9]|3[0-1])\./.test(hostname)) return true;
  return false;
}

/**
 * Resolve the origin used in links that leave LiveCoach, such as invitation
 * and daily brief emails. A stale local development value must never leak
 * into an email generated by a Vercel deployment.
 */
export function publicAppOrigin(requestOrigin?: string): string {
  const deployed =
    process.env.VERCEL === "1" ||
    process.env.VERCEL_ENV === "production" ||
    process.env.VERCEL_ENV === "preview";

  const configured = normalizedOrigin(process.env.NEXT_PUBLIC_APP_URL);
  if (
    configured &&
    (!deployed ||
      (configured.startsWith("https://") && !isLocalOrPrivateOrigin(configured)))
  ) {
    return configured;
  }

  if (deployed) {
    const productionDomain = normalizedOrigin(
      process.env.VERCEL_PROJECT_PRODUCTION_URL
    );
    if (
      productionDomain?.startsWith("https://") &&
      !isLocalOrPrivateOrigin(productionDomain)
    ) {
      return productionDomain;
    }
    return CANONICAL_PRODUCTION_ORIGIN;
  }

  const request = normalizedOrigin(requestOrigin);
  return request || CANONICAL_PRODUCTION_ORIGIN;
}

