-- Assigned salespeople can edit a shared deal, but its history retains the
-- original record owner. Permit only the matching history generated by a
-- database trigger; ordinary direct inserts retain the existing owner rule.
create policy "Members record assigned opportunity history"
on public.opportunity_events
for insert to authenticated
with check (
  pg_trigger_depth() > 0
  and exists (
    select 1
    from public.opportunities opportunity
    join public.workspace_members member
      on member.workspace_id = opportunity.workspace_id
      and member.user_id = (select auth.uid())
      and member.status = 'active'
    where opportunity.id = opportunity_events.opportunity_id
      and opportunity.workspace_id = opportunity_events.workspace_id
      and opportunity.owner_id = opportunity_events.owner_id
      and opportunity.company_id is not distinct from opportunity_events.company_id
      and opportunity.visibility = opportunity_events.visibility
      and opportunity.visibility = 'team'
      and coalesce(opportunity.opportunity_type, 'revenue') = 'revenue'
      and (
        opportunity.assigned_to_user_id = (select auth.uid())
        or member.role in ('owner', 'manager')
      )
  )
);
