-- Give every salesperson one private booking link and let the approval-only
-- next-move queue prepare an optional personal voice-note companion. Audio
-- stays in the existing private Storage bucket and is never generated by a
-- background job.

alter table public.salesperson_profiles
  add column if not exists booking_url text;

alter table public.salesperson_profiles
  drop constraint if exists salesperson_profiles_booking_url_check,
  add constraint salesperson_profiles_booking_url_check check (
    booking_url is null
    or (
      length(btrim(booking_url)) between 12 and 500
      and booking_url ~* '^https://'
    )
  );

comment on column public.salesperson_profiles.booking_url is
  'The signed-in salesperson own HTTPS booking link. It is never borrowed from another workspace member.';

-- Preserve the one existing campaign link only when a salesperson owns
-- exactly one distinct HTTPS value. Multiple or shared-looking values remain
-- unset so the user must choose explicitly in My Sales Setup.
with unambiguous_owned_links as (
  select
    workspace_id,
    owner_id as user_id,
    min(btrim(booking_url)) as booking_url
  from public.outreach_campaigns
  where owner_id is not null
    and booking_url is not null
    and btrim(booking_url) ~* '^https://'
  group by workspace_id, owner_id
  having count(distinct btrim(booking_url)) = 1
)
update public.salesperson_profiles profile
set booking_url = links.booking_url,
    updated_at = now()
from unambiguous_owned_links links
where profile.workspace_id = links.workspace_id
  and profile.user_id = links.user_id
  and nullif(btrim(coalesce(profile.booking_url, '')), '') is null;

alter table public.email_assistant_drafts
  add column if not exists meeting_cta_recommended boolean not null default false,
  add column if not exists booking_url text,
  add column if not exists voice_script text,
  add column if not exists voice_status text not null default 'none',
  add column if not exists voice_audio_path text,
  add column if not exists voice_audio_mime text,
  add column if not exists voice_generated_at timestamptz,
  add column if not exists voice_script_hash text,
  add column if not exists voice_public_token uuid not null default gen_random_uuid(),
  add column if not exists voice_model_id text,
  add column if not exists voice_provider_voice_id text,
  add column if not exists voice_provider_request_id text,
  add column if not exists voice_estimated_seconds integer,
  add column if not exists voice_character_count integer,
  add column if not exists voice_estimated_cost_gbp numeric(8,6),
  add column if not exists voice_error text,
  add column if not exists voice_script_approved_at timestamptz,
  add column if not exists voice_script_approved_by uuid,
  add column if not exists voice_script_approved_hash text;

alter table public.email_assistant_drafts
  drop constraint if exists email_assistant_drafts_booking_url_check,
  add constraint email_assistant_drafts_booking_url_check check (
    booking_url is null
    or (
      meeting_cta_recommended
      and length(btrim(booking_url)) between 12 and 500
      and booking_url ~* '^https://'
    )
  ),
  drop constraint if exists email_assistant_drafts_voice_status_check,
  add constraint email_assistant_drafts_voice_status_check check (
    voice_status in ('none', 'script_ready', 'generating', 'ready', 'failed')
  ),
  drop constraint if exists email_assistant_drafts_voice_script_check,
  add constraint email_assistant_drafts_voice_script_check check (
    voice_script is null or length(btrim(voice_script)) between 1 and 1200
  ),
  drop constraint if exists email_assistant_drafts_voice_seconds_check,
  add constraint email_assistant_drafts_voice_seconds_check check (
    voice_estimated_seconds is null
    or voice_estimated_seconds between 20 and 90
  ),
  drop constraint if exists email_assistant_drafts_voice_character_count_check,
  add constraint email_assistant_drafts_voice_character_count_check check (
    voice_character_count is null
    or voice_character_count between 1 and 1200
  ),
  drop constraint if exists email_assistant_drafts_voice_cost_check,
  add constraint email_assistant_drafts_voice_cost_check check (
    voice_estimated_cost_gbp is null
    or voice_estimated_cost_gbp between 0 and 0.075
  ),
  drop constraint if exists email_assistant_drafts_voice_approval_check,
  add constraint email_assistant_drafts_voice_approval_check check (
    (
      voice_script_approved_at is null
      and voice_script_approved_by is null
      and voice_script_approved_hash is null
    )
    or (
      voice_script_approved_at is not null
      and voice_script_approved_by = owner_id
      and length(voice_script_approved_hash) = 64
    )
  ),
  drop constraint if exists email_assistant_drafts_voice_ready_check,
  add constraint email_assistant_drafts_voice_ready_check check (
    voice_status <> 'ready'
    or (
      voice_audio_path is not null
      and voice_audio_mime = 'audio/mpeg'
      and voice_generated_at is not null
      and length(voice_script_hash) = 64
    )
  );

create unique index if not exists email_assistant_drafts_voice_token_unique
  on public.email_assistant_drafts (voice_public_token);

create unique index if not exists email_assistant_one_voice_generation_per_owner_idx
  on public.email_assistant_drafts (workspace_id, owner_id)
  where voice_status = 'generating';

create index if not exists email_assistant_voice_ready_owner_idx
  on public.email_assistant_drafts (workspace_id, owner_id, updated_at desc)
  where voice_status = 'ready';

create or replace function public.validate_email_assistant_booking_owner()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  if new.booking_url is not null and not exists (
    select 1
    from public.salesperson_profiles profile
    where profile.workspace_id = new.workspace_id
      and profile.user_id = new.owner_id
      and profile.booking_url = new.booking_url
  ) then
    raise exception 'the next-move booking link does not belong to this salesperson';
  end if;
  return new;
end;
$$;

drop trigger if exists email_assistant_booking_owner_guard
  on public.email_assistant_drafts;
create trigger email_assistant_booking_owner_guard
  before insert or update of workspace_id, owner_id, booking_url
  on public.email_assistant_drafts
  for each row execute function public.validate_email_assistant_booking_owner();

revoke execute on function public.validate_email_assistant_booking_owner()
  from public, anon, authenticated;

comment on column public.email_assistant_drafts.booking_url is
  'Immutable-at-generation snapshot of the draft owner personal booking link. Handoff revalidates it against the current profile.';
comment on column public.email_assistant_drafts.voice_script is
  'Free editable spoken reply generated from the same exact inbound email and owner-scoped CRM facts.';
comment on column public.email_assistant_drafts.voice_audio_path is
  'Private Storage path for explicitly approved audio. Never expose this path directly.';
comment on column public.email_assistant_drafts.voice_public_token is
  'Unguessable bearer token for the separate no-index personal listening page.';
